baseURL = "https://duclx123.github.io/fcj-workshop-template-main/"
relativeURLs = true
canonifyURLs = true

languageCode = "vi"
defaultContentLanguage = "vi"
defaultContentLanguageInSubdir = false
hasCJKLanguage = true

theme = "hugo-theme-learn"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  themeVariant = "workshop"
  editURL = ""
  description = ""
  author = "ducnqse182087@fpt.edu.vn"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false

# ------------------------------
# 🟢 Định nghĩa ngôn ngữ
# ------------------------------
[languages]

  [languages.vi]
  title = "Báo cáo thực tập"
  weight = 1
  languageName = "Tiếng Việt"

  [[languages.vi.menu.shortcuts]]
  name = "<i class='fab fa-facebook'></i> AWS Study Group"
  identifier = "AWS Study Group FB"
  url = "https://www.facebook.com/groups/awsstudygroupfcj/"
  weight = 20

  [languages.en]
  title = "Internship Report"
  weight = 2
  languageName = "English"

  [[languages.en.menu.shortcuts]]
  name = "<i class='fab fa-facebook'></i> AWS Study Group"
  identifier = "AWS Study Group FB"
  url = "https://www.facebook.com/groups/awsstudygroupfcj/"
  weight = 20

# ------------------------------
# 🧱 Markdown renderer settings
# ------------------------------
[markup.goldmark.renderer]
unsafe = true
