baseURL = "https://duclx123.github.io/fcj-workshop-template-main/"
relativeURLs = true
canonifyURLs = true

languageCode = "vi"
defaultContentLanguage = "vi"
defaultContentLanguageInSubdir = false
hasCJKLanguage = true

# Theme
theme = "hugo-theme-learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "workshop"
  # GitHub repo link
  editURL = ""
  description = ""
  author = "ducnqse182087@fpt.edu.vn"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false

# -----------------------------
# 🌐 Multilingual configuration
# -----------------------------
[languages]
  [languages.en]
  title = "Internship Report"
  weight = 1
  languageName = "English"

  [[languages.en.menu.shortcuts]]
  name = "<i class='fab fa-facebook'></i> AWS Study Group"
  identifier = "AWS Study Group FB"
  url = "https://www.facebook.com/groups/awsstudygroupfcj/"
  weight = 20

  [languages.vi]
  title = "Báo cáo thực tập"
  weight = 2
  languageName = "Tiếng Việt"

  [[languages.vi.menu.shortcuts]]
  name = "<i class='fab fa-facebook'></i> AWS Study Group"
  identifier = "AWS Study Group FB"
  url = "https://www.facebook.com/groups/awsstudygroupfcj/"
  weight = 20

# Markdown
[markup.goldmark.renderer]
unsafe = true
